#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	addgroup --system --quiet ntp
	adduser --system --quiet --ingroup ntp --no-create-home --home /nonexistent ntp
	chown ntp:ntp /var/lib/ntp /var/log/ntpstats

	# Bug#863857, the experimental version shipped a broken systemd wrapper
	# writing a bogus PIDFILE on the root partition
	if [ "$2" = "1:4.2.8p10+dfsg-3+exp2" ]; then
		rm -f /-g
	fi
fi

if [ "$1" = "triggered" ]; then
	# The default configuration uses a leapfile from tzdata
	# restart ntp on changes
	invoke-rc.d ntp try-restart || true
fi

installinit_error() {
	exit $?
}

# Automatically added by dh_systemd_enable/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ntp.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ntp.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ntp.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ntp.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.1.0-1
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/usr.sbin.ntpd"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.sbin.ntpd"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/etc/init.d/ntp" ]; then
		update-rc.d ntp defaults >/dev/null
		invoke-rc.d ntp start || installinit_error
	fi
fi
# End automatically added section

