#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/ntp" ] ; then
	chmod +x "/etc/init.d/ntp" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -x "/etc/init.d/ntp" ] ; then
	invoke-rc.d ntp stop || installinit_error
fi
# End automatically added section
