#!/bin/sh

set -e

installinit_error() {
	status=$?
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ntpd.pid && exit 0
	exit $status
}

# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/ntp" ] ; then
	invoke-rc.d ntp stop || installinit_error
fi
# End automatically added section

